### ISSUE TITLE
And Gungnir don't Show up after Equipment 

### ISSUE THREAD

**Issue by RebalClause** [andtheherois/3DSS-Gungnir#1]
https://drive.google.com/file/d/1R90idrk01t67tevgmfP6O-ydEzM4lyFr/view?usp=drivesdk

And GEWEHR crash after equip the weapon

**Comment by andtheherois** [comment]
sounds like youre missing base mods.

**Comment by RebalClause** [comment]
Can you give me what the base mod?

**Comment by andtheherois** [comment]
all base mod links are in the readme

**Comment by RebalClause** [comment]
I've already downloaded the scops and original mods that I read. 3D scops mod, if you load it, put it below, if it's a weapon mod, put it above, like the picture of the loader for mo2. I've tried everything, but it's the same gauss and Gungnir I don't know what's missing... Gewehr, I don't know when to install it. 3D shader scope crash when using this weapon
